export const Users = [
    {
      id:1,
      profilePicture: "assets/person/picture-1.jpg",
      username: "Mark Zuckerberg",
    },
    {
      id:2,
      profilePicture: "assets/person/picture-2.jpg",
      username: "Bill Gates",
    },
    {
      id:3,
      profilePicture: "assets/person/picture-3.jpg",
      username: "jack ma",
    },
    {
      id:4,
      profilePicture: "assets/person/picture-4.jpg",
      username: "Taylor Swift",
    },
    {
      id:5,
      profilePicture: "assets/person/picture-5.jpg",
      username: "Pham Nhat Vuong",
    },
    {
      id:6,
      profilePicture: "assets/person/picture-6.jpg",
      username: "DanFoolish",
    },
    {
      id:7,
      profilePicture: "assets/person/picture-7.jpg",
      username: "Son Tung M-TP",
    },
    {
      id:8,
      profilePicture: "assets/person/picture-8.jpg",
      username: "Elon Musk",
    },
    {
      id:9,
      profilePicture: "assets/person/picture-9.jpg",
      username: "Jeff Bezos",
    },
    {
      id:10,
      profilePicture: "assets/person/picture-10.jpg",
      username: "WARREN BUFFETT",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/posts/1.jpg",
      date: "5 phút trước",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/posts/2.jpg",
      date: "15 phút trước",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/posts/3.jpg",
      date: "1 giờ trước",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/posts/4.jpg",
      date: "4 giờ trước",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/posts/5.jpg",
      date: "5 giờ trước",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/posts/6.jpg",
      date: "1 ngày trước",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/posts/7.jpg",
      date: "2 ngày trước",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/posts/8.jpg",
      date: "3 ngày trước",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/posts/9.jpg",
      date: "5 ngày trước",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/posts/10.jpg",
      date: "1 tuần trước",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];